### PR TITLE
Show runtime version in `Kind` column of `activation list`

### PR DESCRIPTION
**Pull request by satyarohith**
Screenshot 2020-08-11 at 6 52 42 PM

### CODE REVIEW

**Comment by joshuaauerbachwatson** [comment]
This PR is on the wrong repo.  @rabbah I thought you were taking steps to cut off access to this legacy repo?   The correct one is under `nimbella` not `nimbella-corp`.

**Comment by rabbah** [comment]
I can’t stop others from forming or creating a PR. But this PR should fail to commit.

**Comment by joshuaauerbachwatson** [comment]
Ok.   We'll have to be satisfied with that.   @satyarohith set your upstream to `nimbella/aio-cli-plugin-runtime` (or re-fork) and re-stage the PR.   Thanks.

**Comment by satyarohith** [comment]
I will make a PR to `nimbella/aio-cli-plugin-runtime`.

**Pull request closed without merging**
